### ISSUE TITLE
Customize tagged view in patterns website

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/green-software-patterns#113] opened 2022-10-14 14:11 UTC
Customize the tagged page view:

- Instead of description show some more meaningful text.
- Ideally show some more information, tags.

![Image](https://user-images.githubusercontent.com/897523/195867540-e14f1a0b-acf2-4842-b17e-e270e7d660a7.png)

**Comment by zanete** [comment] 2022-10-21 11:32
Can I clarify what this is about? 
- (1) Assuming that instead of the word "Description" under each result here https://patterns.greensoftware.foundation/tags/ it should show the actual description of the resulting doc, e.g. "If service downtimes are acceptable it's better to not strive for highest availability but to design the solution according to real business needs. Lower availability guarantees can help reduce energy consumption by using less infrastructure components." should appear under "[Match your service level objectives to business needs](https://patterns.greensoftware.foundation/catalog/cloud/match-slo)" 
- (2) "Ideally show some more information, tags." By Tags it's meant to have all the other tags that doc is associated with, e.g for "Match your service level objectives to business needs" it should show [Cloud](https://patterns.greensoftware.foundation/tags/cloud)[Reliability/Availability](https://patterns.greensoftware.foundation/tags/reliability-availability)[Monitoring](https://patterns.greensoftware.foundation/tags/monitoring)

**Comment by zanete** [comment] 2022-10-21 12:40
(1) @osamajandali to investigate and see what can be done, but hasn't started yet. If the above is not possible will re-discuss

**Comment by zanete** [comment] 2022-10-31 14:14
There is a risk that this might not be done before COP, to be confirmed next week

**Comment by osamajandali** [comment] 2022-11-06 19:46
So the solution turns out to be very simple 😄 
You need only to add a description in frontmatter of each page file.
here is an example
https://github.com/Green-Software-Foundation/green-software-patterns/blob/main/docs/catalog/ai/serverless-model-development.md?plain=1#L6
so once all the pages are updated with this frontmatter, this issue will be fixed

**Comment by holanita** [comment] 2022-11-07 07:46
@osamajandali thanks that's good news I guess. can you do this before cop? cc'ing @zanete so she is aware

**Comment by zanete** [comment] 2022-11-07 11:26
@osamajandali can you clarify that this is something you will do or you provided an example for @holanita so that she (or someone else in the team) can do it?

**Comment by jawache** [comment] 2022-11-07 12:20
@holanita so I think the ask her is for Bill or someone from the patterns team to go through all the existing patters and add a short description at the top like @osamajandali showed how in here: https://github.com/Green-Software-Foundation/green-software-patterns/blob/main/docs/catalog/ai/serverless-model-development.md?plain=1#L6

@osamajandali can't do this, only the people who know the patterns can do this.

**Comment by holanita** [comment] 2022-11-07 12:27
@dubrie @greenhsu123 do you have capacity to add a short description to each pattern as described above? alternatively, if you could list the ones you can take care of, we could ask the team tomorrow to handle the rest.

**Comment by greenhsu123** [comment] 2022-11-07 13:16
Sure, I can do the cloud ones.

**Comment by dubrie** [comment] 2022-11-08 00:10
Just to clarify from my perspective, we have a description section in each of the patterns already. Is the ask to create a second, shorter, description that goes in the front matter section?  Is it possible to use the description as it is today or do we want to re-write new ones for every pattern?

**Comment by holanita** [comment] 2022-11-08 12:44
I had the same understanding @zanete. if this is just a copy-paste job, I can do this myself if no one else has time for this.

**Comment by holanita** [comment] 2022-11-08 16:51
This has been discussed in today's team meeting. We'll go for the copy-paste option. I will do this tomorrow.

**Comment by holanita** [comment] 2022-11-09 13:43
Okay so I've just submitted a PR for AI and WEB, but this seems a bit more tricky than expected. 

1) It's interesting to look at all the descriptions at the same time. I might be wrong but now it feels like some describe the problem, while some describe the solution or maybe both. 
2) I have shortened some descriptions and kept a few long ones. Might be best to test a long one first to see if something gets cut off - since we don't know the exact character limits (?).
3) I ran out of time and Cloud seems scary :) @greenhsu123 do you still have time to process them? If not, I can continue in the evening. Will be back in about 4 hours!

**Comment by greenhsu123** [comment] 2022-11-09 14:02
@holanita ah... i am in Asia at the moment, it will have to wait till tomorrow am for me! could you make a start from the top? and i can catch up from the bottom when i wake up tomorrow :)

**Comment by holanita** [comment] 2022-11-09 18:40
No worries, I've just done Cloud too. @dubrie for Cloud I have used the original descriptions in most cases. Some have special characters like colons or urls, so I have removed some sentences from those descriptions. 

(I forgot that I should have committed to dev from the beginning so most of them are in a new branch sorry. I had 1 accidental commit [in dev](https://github.com/Green-Software-Foundation/green-software-patterns/compare/main...dev) and couldn't find away to delete it. Can you do it form pls?)

**Comment by holanita** [comment] 2022-11-10 06:19
Thanks for reviewing the PR @dubrie. Just checked all the tags on the website everything seems fine.

**Closed by holanita** 2022-11-10 06:19 UTC
Labels: enhancement, website
